/* Generated By:JavaCC: Do not edit this line. XTMParserTreeConstants.java Version 5.0 */
package javacc.parsexml;

public interface XTMParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPARSEXTM = 1;
  public int JJTPARSETOPICMAP = 2;
  public int JJTPARSETOPIC = 3;
  public int JJTPARSETOPICISTANCEOF = 4;
  public int JJTPARSETOPICNAME = 5;
  public int JJTPARSENAMEVARIANT = 6;
  public int JJTPARSETOPICNAMEVARIANTSCOPE = 7;
  public int JJTPARSETOPICOCCURENCE = 8;
  public int JJTPARSETOPICOCCURENCETYPE = 9;
  public int JJTPARSETOPICOCCURENCESCOPE = 10;
  public int JJTPARSEASSOCIATION = 11;
  public int JJTPARSEASSOCIATIONTYPE = 12;
  public int JJTPARSEASSOCIATIONROLE = 13;
  public int JJTPARSEASSOCIATIONROLETYPE = 14;
  public int JJTPARSETOPICID = 15;
  public int JJTPARSENAMEVALUE = 16;
  public int JJTPARSETOPICNAMEVARIANTRESDATA = 17;
  public int JJTPARSETOPICOCCURENCERESDATA = 18;
  public int JJTPARSETOPICSUBJLOC = 19;
  public int JJTPARSETOPICSUBJIDENTIF = 20;


  public String[] jjtNodeName = {
    "start",
    "parseXTM",
    "parseTopicMap",
    "parseTopic",
    "parseTopicIstanceOf",
    "parseTopicName",
    "parseNameVariant",
    "parseTopicNameVariantScope",
    "parseTopicOccurence",
    "parseTopicOccurenceType",
    "parseTopicOccurenceScope",
    "parseAssociation",
    "parseAssociationType",
    "parseAssociationRole",
    "parseAssociationRoleType",
    "parseTopicID",
    "parseNameValue",
    "parseTopicNameVariantResData",
    "parseTopicOccurenceResData",
    "parseTopicSubjLoc",
    "parseTopicSubjIdentif",
  };
}
/* JavaCC - OriginalChecksum=ffe417faa509a0856b7309fbc1fd3265 (do not edit this line) */
