/* Generated By:JJTree&JavaCC: Do not edit this line. XTMParserConstants.java */
package javacc.parsexml;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XTMParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 7;
  /** RegularExpression Id. */
  int DIGIT = 8;
  /** RegularExpression Id. */
  int VALID_URL_SYMBOLS = 9;
  /** RegularExpression Id. */
  int FILE_START = 10;
  /** RegularExpression Id. */
  int START_TOPIC_MAP = 11;
  /** RegularExpression Id. */
  int START_TOPIC = 12;
  /** RegularExpression Id. */
  int END_TOPIC = 13;
  /** RegularExpression Id. */
  int START_ASSOCIATION = 14;
  /** RegularExpression Id. */
  int END_ASSOCIATION = 15;
  /** RegularExpression Id. */
  int START_ROLE = 16;
  /** RegularExpression Id. */
  int END_ROLE = 17;
  /** RegularExpression Id. */
  int TAG_END = 18;
  /** RegularExpression Id. */
  int END_TOPIC_MAP = 19;
  /** RegularExpression Id. */
  int START_SUBJECT_LOCATOR = 20;
  /** RegularExpression Id. */
  int START_SUBJECT_IDENTIFIER = 21;
  /** RegularExpression Id. */
  int START_INSTANCE_OF = 22;
  /** RegularExpression Id. */
  int END_INSTANCE_OF = 23;
  /** RegularExpression Id. */
  int START_TOPIC_REF = 24;
  /** RegularExpression Id. */
  int START_VARIANT = 25;
  /** RegularExpression Id. */
  int END_VARIANT = 26;
  /** RegularExpression Id. */
  int START_VALUE = 27;
  /** RegularExpression Id. */
  int END_VALUE = 28;
  /** RegularExpression Id. */
  int START_NAME = 29;
  /** RegularExpression Id. */
  int END_NAME = 30;
  /** RegularExpression Id. */
  int START_SCOPE = 31;
  /** RegularExpression Id. */
  int END_SCOPE = 32;
  /** RegularExpression Id. */
  int START_RESOURCE_DATA = 33;
  /** RegularExpression Id. */
  int END_RESOURCE_DATA = 34;
  /** RegularExpression Id. */
  int START_OCCURENCE = 35;
  /** RegularExpression Id. */
  int END_OCCURENCE = 36;
  /** RegularExpression Id. */
  int START_TYPE = 37;
  /** RegularExpression Id. */
  int END_TYPE = 38;
  /** RegularExpression Id. */
  int EXTENDED_ALPHANUMERIC_STRING = 39;
  /** RegularExpression Id. */
  int MULTI_EX_AL_ST = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "<token of kind 6>",
    "<LETTER>",
    "<DIGIT>",
    "<VALID_URL_SYMBOLS>",
    "\"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\"",
    "\"<topicMap xmlns=\\\"http://www.topicmaps.org/xtm/\\\" version=\\\"2.0\\\">\"",
    "\"<topic id=\\\"topic\"",
    "\"</topic>\"",
    "\"<association>\"",
    "\"</association>\"",
    "\"<role>\"",
    "\"</role>\"",
    "\"\\\"/>\"",
    "\"</topicMap>\"",
    "\"<subjectLocator href=\\\"\"",
    "\"<subjectIdentifier href=\\\"\"",
    "\"<instanceOf>\"",
    "\"</instanceOf>\"",
    "\"<topicRef href=\\\"#topic\"",
    "\"<variant>\"",
    "\"</variant>\"",
    "\"<value>\"",
    "\"</value>\"",
    "\"<name>\"",
    "\"</name>\"",
    "\"<scope>\"",
    "\"</scope>\"",
    "\"<resourceData>\"",
    "\"</resourceData>\"",
    "\"<occurrence>\"",
    "\"</occurrence>\"",
    "\"<type>\"",
    "\"</type>\"",
    "<EXTENDED_ALPHANUMERIC_STRING>",
    "<MULTI_EX_AL_ST>",
    "\"\\\">\"",
  };

}
